### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Kenmmm** [bravekingzhang/yours#1]
你的Demo我已经clone下来，AS下面完全跑不起来，看着也不像AS的项目，不知道是你上传的时候的问题，还是什么问题，请自行试一下

**Comment by bravekingzhang** [comment]
文件全部都给了，你可以把yours.iml文件去掉，然后在 clean一下 ，多谢关注！

**Comment by Kenmmm** [comment]
有几个蛋疼的地方，终于改好，可以运行了。。都是新东西，不错

**Comment by bravekingzhang** [comment]
你可以把DT的地方写这这里，方便其他fork的人解决你遇到的问题。

**Comment by Kenmmm** [comment]
一些httpclient的jar包，如果想用AndroidHttpClient，需要 在gradle中的android节点加入useLibrary 'org.apache.http.legacy'，在gradle中加入lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
，不然会有各种蛋疼的问题

**Comment by bravekingzhang** [comment]
可能是你的sdk版本和我的不一样，是否比我的老，这里网络请求是用的volley做的。volley源码在src中，可以看看他的httpstack实现。

**Comment by Kenmmm** [comment]
都比你的高，可能是版本的问题。。如果是6.0这个要写的useLibrary 'org.apache.http.legacy'

**Comment by bravekingzhang** [comment]
我还没用上6.0，之前了解过，他的权限比较复杂，打算在等等。

**Comment by tianshaokai** [comment]
@bravekingzhang 你提交一下 gradle 配置文件吧 ，或者@ThinkWYP 你也可以提交一下你的修改合并一下吧

**Comment by bravekingzhang** [comment]
@tianshaokai build.gradle 文件在的，请仔细查看

**Comment by tianshaokai** [comment]
@bravekingzhang gradle/wrapper 目录文件，这样以后 更新什么的比较方便

**Comment by Kenmmm** [comment]
这个demo直接clone的话是没法运行的

**Comment by tianshaokai** [comment]
@ThinkWYP  你提交一下你的更改吧

**Comment by Kenmmm** [comment]
@bravekingzhang Do you agree？

**Comment by bravekingzhang** [comment]
两位，鉴于你们都有有导入的问题，我自己在我公司的电脑上把zip文件下载下来，然后解压，用android studio导入，**_非常顺利**_，并没有出现你们所谓没法运行。我的方式：
- step1
  在工程下右键，然后
  new->new module->import gradle project
- step2
  然后选择到我们解压的那个目录就OK了（？？你们是否点到了build.gradle？？），比如我的是/Users/brzhang/Downloads/yours-master
- step3
  :yours-master 重命名为你想要的模块，然后finish就可以了。

> 强烈建议两位按照我的方式试一下，我完全没有任何改动直接就导入了，可以直接运行  ：)

**Comment by tianshaokai** [comment]
谢谢 @bravekingzhang  你这里只是上传了一个module，我们的习惯都是导入一个studio project，习惯不一样而已

**Comment by bravekingzhang** [comment]
@tianshaokai 是的，我这并非一个project，只是一个module,所以建议使用我的那种方式导入，因为是很顺利的：）

**Comment by bravekingzhang** [comment]
项目最近加了`realm`，因为这个库要从JCENTER中取，所以，我贴一下我的项目的gradle文件

```
buildscript {

    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
    }
}

allprojects {
    repositories {
        mavenCentral()
        jcenter()
    }
}
```
